---
title: "Pre-Bootcamp Homework"
---

***

Use the computational tools/statistical analysis workflow you are familiar with to perform the following tasks.  By "statistical analysis workflow" I mean something like the following (there are plenty of other ways as well):

- Using SPSS drop-down menus to do the needed calculations and plots and then copying these results into Microsoft Word where you write your analysis.
- Writing a STATA do file to perform the analysis and then copying the results into Google Docs with analysis to create a report.

**Problem Description**:  The `nyc-weather-13.csv` file available from [http://bit.ly/nyc-weather-13](https://ismayc.github.io/poRtland-bootcamp17/nyc-weather-13.csv) contains hourly meteorological data from 2013 for each of the three New York City airports:

  - `EWR` - Newark Liberty International Airport
  - `JFK` - John F. Kennedy International Airport
  - `LGA` - LaGuardia Airport

**Tasks to complete**:
  
1. Produce a plot exploring the relationship between `month` and `temp`.
1. Calculate the minimum temperature recorded for each month across all three airports. 
    - This should result in a dataset with 12 rows and two columns. (One row for each month.)
1. Produce a plot showing how minimum temperature varies across the 12 months.
1. Calculate the minimum temperature recorded for each month FOR EACH OF the three airports. 
    - This should result in a dataset with 36 rows and three columns.  (One row for each month for each airport.)
1. Explore the multivariate relationship between month, airport, and minimum temperature via a statistical graphic.

**Last but not least**:  Produce a report providing the calculations done in table form as well as the graphics made.  Also include a brief discussion about what stands out from the plots and calculations after each of the five tasks above.